### ISSUE TITLE
YandexMobileMetrica, YandexMobileAds break preview for SwiftUI

### ISSUE THREAD

**Issue by iDevPro** [yandexmobile/yandex-ads-sdk-ios#170] opened 2023-08-07 04:51 UTC
It is not possible to use SwiftUI preview mode (Canvas) in the application using the YandexMobileMetrica, YandexMobileAds libraries. The build breaks down until the libraries are removed from the project.

**Comment by aldelank** [comment] 2023-08-14 21:11
Hello, thanks for your message!

We couldn't reproduce your issue on public example app from this repo. So can you please send us empty project with this problem being able to reproduce. And also clarify please are you trying to build on intel or m1?

**Comment by mobile-ads-github** [comment] 2023-08-15 07:15
Hello, thanks for your message!

We couldn't reproduce your issue on public example app from this repo. So can you please send us empty project with this problem being able to reproduce. And also clarify please are you trying to build on intel or m1?

**Comment by iDevPro** [comment] 2023-08-16 12:40
We use this library on m1 macs

**Comment by mobile-ads-github** [comment] 2023-08-25 09:37
Спасибо за Ваше обращение, для разбора создана задача с номером PCODESUP-2228. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number PCODESUP-2228 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment] 2023-08-30 14:00
Hi! Have you checked the build with the new SDK?

**Comment by mobile-ads-github** [comment] 2023-08-30 15:38
Спасибо за Ваше обращение, для разбора создана задача с номером TEST-309973. Мы ознакомимся и вернемся с ответом в течение 2 дней, возможно запросим дополнительную информацию.

Thank you for your message, a task with the number TEST-309973 has been created for analysis. We will get acquainted and return with the answer within 2 days, we may request additional information.

**Comment by mobile-ads-github** [comment] 2023-10-10 12:22
Closing, as now additional information was provided.

**Closed by mobile-ads-github** 2023-10-10 12:22 UTC
Labels: transmitted

**Comment by yishair-investing** [comment] 2025-06-12 15:58
I still see this issue, is there an update on it?
